#!/bin/bash

echo "Railway Deployment Script"
echo "========================"
echo ""
echo "Since Railway CLI requires interactive input, please follow these steps:"
echo ""
echo "1. Create a new Railway project:"
echo "   railway init"
echo ""
echo "2. When prompted:"
echo "   - Select your workspace"
echo "   - Choose 'Empty Project'"
echo "   - Enter project name: claude-cloud-service"
echo ""
echo "3. Link your GitHub repo:"
echo "   railway link"
echo ""
echo "4. Connect to GitHub:"
echo "   railway run railway connect github"
echo ""
echo "5. Set environment variables:"
echo "   railway variables set ANTHROPIC_API_KEY=your-api-key"
echo "   railway variables set JWT_SECRET=$(openssl rand -base64 32)"
echo "   railway variables set SESSIONS_DIR=/app/sessions"
echo "   railway variables set NODE_ENV=production"
echo ""
echo "6. Deploy:"
echo "   railway up"
echo ""
echo "Your GitHub repository is ready at: https://github.com/adnanakil/claude-cloud-service"